public class GoogleDriveApi_File {
    public String kind{get;set;}
    public String id{get;set;} // //
    public String name{get;set;}
    public String mimeType{get;set;}
    public String description{get;set;}
    public Boolean starred{get;set;}
    public Boolean trashed{get;set;}
    public Boolean explicitlyTrashed{get;set;}
    public Datetime trashedTime{get;set;}
    public String version{get;set;}
    public String webContentLink{get;set;}
    public String webViewLink{get;set;}
    public String iconLink{get;set;}
    public Datetime createdTime{get;set;}
    public Datetime modifiedTime{get;set;}
    public String teamDriveId{get;set;}
    public Boolean shared{get;set;}
    public String originalFilename{get;set;}
    public String fullFileExtension{get;set;}    
    public String fileExtension{get;set;}        
    //public List<String> parents{get;set;}
    //public String properties{get;set;}
    //public String appProperties{get;set;}
    
}